version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  sourcehawk-scan:
    lang: dockerfile
    handler: ./sourcehawk-scan
    image: sourcehawk-scan:latest
  validate-config:
    lang: dockerfile
    handler: ./validate-config
    image: sourcehawk-validate-config:latest
