version: 1.0

provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:

  scan:
    lang: golang-middleware
    handler: ./scan
    image: sourcehawk-scan:0.1.0
    constraints:
      - "node.platform.os == linux"
    labels:
      sourcehawk-version: 0.1.5
