version: 1.0

provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

configuration:
  copy:
    - bin

functions:
  sourcehawk-scan:
    lang: golang-middleware-busybox
    handler: ./scan
    image: sourcehawk-scan:0.1.0
    constraints:
      - "node.platform.os == linux"
