FROM optumopensource/sourcehawk-openfaas-scan:0.1.0

LABEL sourcehawk.version="0.1.5"
LABEL sourcehawk.openfaas.version="0.1.0"
LABEL description="Sourcehawk OpenFaaS Scan function: Perform sourcehawk scans on github repositories with ease."
