FROM optumopensource/sourcehawk-openfaas-validate-config:0.1.0

LABEL sourcehawk.version="0.1.5"
LABEL sourcehawk.openfaas.version="0.1.0"
LABEL description="Sourcehawk OpenFaaS Validate Config function: Validate sourcehawk configuration files on demand."
